image: texlive/texlive

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt -y update &> apt-update.lg
    - apt -y install python3-pip &> apt-install-pip.lg
    - cat /etc/*-release
    - python3 --version
    - pip3 --version
    - python3 -m pip install glob2 &> glob2-install.lg
    - python3 -m pip install bibtexparser &> bibtexparser.lg
    - export PYTHONPATH="${PYTHONPATH}:."
    - python3 ./owl/check.py &> check.lg
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - "*.html"
      - "*.lg"

deploy:
  stage: deploy
  script:
    - latexmk -C
    - latexmk -pdf -interaction=nonstopmode demo.tex
  artifacts:
    expire_in: 1 mos
    paths:
      - "all.bib"
      - "demo.tex"
      - "demo.pdf"
